club_club:
    resource: "@ClubBundle/Resources/config/routing/club.yml"
    prefix:   /club

club_homepage:
    path:     /
    defaults: { _controller: ClubBundle:Default:index }

club_av3:
            resource: "@ClubBundle/Resources/config/routing/av3.yml"
            prefix:   /av3

club_contact:
    resource: "@ClubBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

club_av2:
        resource: "@ClubBundle/Resources/config/routing/av2.yml"
        prefix:   /av2

club_av1:
        resource: "@ClubBundle/Resources/config/routing/av1.yml"
        prefix:   /av1

club_presentation:
        resource: "@ClubBundle/Resources/config/routing/presentation.yml"
        prefix:   /presentation

club_club_sup:
        resource: "@ClubBundle/Resources/config/routing/club_sup.yml"
        prefix:   /club_sup

club_rcvl:
        resource: "@ClubBundle/Resources/config/routing/rcvl.yml"
        prefix:   /rcvl

club_ara:
        resource: "@ClubBundle/Resources/config/routing/ara.yml"
        prefix:   /ara