club_club:
    resource: "@ClubBundle/Resources/config/routing/club.yml"
    prefix:   /club

club_homepage:
    path:     /
    defaults: { _controller: ClubBundle:Default:index }

     club_av3:
            resource: "@ClubBundle/Resources/config/routing/av3.yml"
            prefix:   /av3

