av3_index:
    path:     /
    defaults: { _controller: "ClubBundle:av3:index" }
    methods:  GET

av3_show:
    path:     /{id}/show
    defaults: { _controller: "ClubBundle:av3:show" }
    methods:  GET

av3_new:
    path:     /new
    defaults: { _controller: "ClubBundle:av3:new" }
    methods:  [GET, POST]

av3_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClubBundle:av3:edit" }
    methods:  [GET, POST]

av3_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClubBundle:av3:delete" }
    methods:  DELETE
