evenements_index:
    path:     /
    defaults: { _controller: "ClubBundle:Evenements:index" }
    methods:  GET

evenements_new:
    path:     /new
    defaults: { _controller: "ClubBundle:Evenements:new" }
    methods:  [GET, POST]

evenements_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClubBundle:Evenements:edit" }
    methods:  [GET, POST]

evenements_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClubBundle:Evenements:delete" }
    methods:  DELETE
