evrcvl_index:
    path:     /
    defaults: { _controller: "ClubBundle:EvRcvl:index" }
    methods:  GET

evrcvl_new:
    path:     /new
    defaults: { _controller: "ClubBundle:EvRcvl:new" }
    methods:  [GET, POST]

evrcvl_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClubBundle:EvRcvl:edit" }
    methods:  [GET, POST]

evrcvl_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClubBundle:EvRcvl:delete" }
    methods:  DELETE
